from calculator import *
from calculator.scientific import *
a = int(input("Enter 'a' value: "))
b = int(input("Enter 'b' value: "))
print(f"Sum is {arithmetic.addition(a,b)}")
print(f"Difference is {arithmetic.subtraction(a,b)}")
print(f"Product is {arithmetic.multiplication(a,b)}")
print(f"True division is {arithmetic.truedivision(a,b)}")
print(f"The quotient is {arithmetic.divide(a,b)[0]} and remainder is {arithmetic.divide(a,b)[1]}")
print(f"The square of a is {power.square(a)}")
print(f"The cube of a is {power.cube(a)}")
print(f"The value of a to the power b is {power.custom(a,b)}")
bool1 = input("Enter True or False bool1: ")
bool2 = input("Enter True or False bool2: ")
print(f"bool1 and bool2 is {logical.andgate(bool1,bool2)}")
print(f"bool1 or bool2 is {logical.orgate(bool1,bool2)}")
print(f"bool1 nor bool2 is {logical.norgate(bool1,bool2)}")
print(f"bool1 nand bool2 is {logical.nandgate(bool1,bool2)}")
print(f"bool1 xor bool2 is {logical.xorgate(bool1,bool2)}")